# Generated by Django 3.0.3 on 2020-02-25 18:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClassYear',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classYear', models.CharField(choices=[('2019', '2019'), ('2018', '2018'), ('2017', '2017'), ('2016', '2016'), ('2015', '2015'), ('Other', 'Other')], default='2018', max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='Friend',
            fields=[
                ('name', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('hobby', models.CharField(max_length=255)),
                ('food', models.CharField(max_length=255)),
                ('drink', models.CharField(max_length=255)),
                ('ClassYear', models.ForeignKey(default='Fasilkom', on_delete=django.db.models.deletion.CASCADE, to='homepage.ClassYear')),
            ],
        ),
    ]
